export const USER_SIGN_IN_API = "USER_SIGN_IN_API";

export const USER_SIGNIN_JIRA = "USER_SIGNIN_JIRA";

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
export const CREATE_PROJECT = "CREATE_PROJECT";
