export const USER_SIGN_IN_API = "USER_SIGN_IN_API";

export const USER_SIGNIN_JIRA = "USER_SIGNIN_JIRA";

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
export const CREATE_PROJECT = "CREATE_PROJECT";

export const GET_ALL_PROJECTS_SAGA = "GET_ALL_PROJECTS_SAGA";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";

export const UPDATE_PROJECT_SAGA = "UPDATE_PROJECT_SAGA";

export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const SUBMIT_EDIT_FORM = "SUBMIT_EDIT_FORM";

export const EDIT_PROJECT_JIRA = "EDIT_PROJECT_JIRA";

export const GET_USER_SAGA = "GET_USER_SAGA";
export const GET_USER_SEARCH = "GET_USER_SEARCH";
export const ADD_USER_PROJECT_SAGA = "ADD_USER_PROJECT_SAGA";
export const DELETE_USER_FROM_PROJECT_SAGA = "DELETE_USER_FROM_PROJECT_SAGA";
export const GET_PROJECT_DETAIL_SAGA = "GET_PROJECT_DETAIL_SAGA";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";

export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";

export const GET_ALL_PROJECTS_SAGA_LIST = "GET_ALL_PROJECTS_SAGA_LIST";
export const GET_ALL_PROJECT_ACTION = "GET_ALL_PROJECT_ACTION";

export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
